d <- read_delim("day14A.txt", col_names = FALSE, delim=' -> ')
df<-df_from_vector_of_strings(d$X1) 
df$x3<-d$X3

polymer<-"FNFPPNKPPHSOKFFHOFOC"
n<-10

pairTable<-df %>% select(-x3)
pairTable$z=1
c<-data.frame(z=1,n=1:10,res="")
pairTable %>% full_join(c) %>% select(-z)->pairTable

# A

# string generated by the pair x1,x2 after n steps
assemble<-function(x1,x2,n){
  if(n==0) return(paste0(x1,x2))
  xx1<-x1;xx2<-x2;nn<-n
  if(nrow(df %>% filter(x1==xx1,x2==xx2))==0) return(paste0(xx1,xx2))
  ans<-pairTable %>% filter(x1==xx1,x2==xx2,n==nn) %>% select(res) %>% unlist %>% unname
  if(ans=="") 
  {
    x3<-df %>% filter(x1==xx1,x2==xx2) %>% select(x3) %>% unlist %>% unname
    s1<-assemble(xx1,x3,nn-1)
    s2<-assemble(x3,xx2,nn-1)
    ans<-paste0(substr(s1,1,nchar(s1)-1),s2)
    pairTable %>% mutate(res=if_else(
      x1==xx1 & x2==xx2 & n==nn,ans,res
    ))->>pairTable
  }
  return(ans)
}

pmap(pairTable %>% select(-res),assemble)

df_from_vector_of_strings(polymer) %>% unlist %>% as.vector ->input

table(input)

solTotal<-table(str_split(assemble(input[1],input[2],n),'') %>% unlist)
#as.data.frame(sol) ->solTotal

for(j in 3:length(input)){
  sol<-table(str_split(assemble(input[j-1],input[j],n),'') %>% unlist)
  solTotal %>% bind_rows(sol)->solTotal
}


solTotal %>% colSums() ->sums
# each letter from input is counted twice but the first and the last ones

table(input)->tabInput
for(j in 1:10){
  if(names(sums)[j] %in% names(tabInput)){
    sums[j]<-sums[j]-tabInput[names(tabInput)==names(sums)[j]]
  }
}
sums<-sums+as.integer(names(sums) %in% c("C","F"))
max(sums)-min(sums)

# 2975





# B

# Necessary for long integers:
options(digits = 20)

# strings are too long if we continue to store them in the logic of part A

# Let's count the number of appearances of each pair of characters after 0,10,20,30,40 steps
names(sums)
pairs<-full_join(data.frame (a=names(sums),c=0),data.frame (b=names(sums),c=0))

pairs$step10<-0
pairs$step20<-0
pairs$step30<-0
pairs$step40<-0

# How many appearances of pair(a,b) in input
for(j in 2:length(input)){
  pairs %>% mutate(c=if_else(a==input[j-1] & b==input[j],c+1,c))->pairs
}

# checks
pairs %>% head
pairTable %>% head
pairTable %>% is.na %>% sum
pairs %>% is.na %>% sum

# How many appearances of pair(a,b) after 10 steps
fill10<-function(a,c,b){
  if(c>0){
    cc<-c
    s<-pairTable %>% filter(x1==a,x2==b,n==10) %>% select(res) %>% 
      unlist %>% unname
    inputs<-str_split(s,'') %>% unlist
    #print(inputs)
    for(j in 2:length(inputs)){
      # pairs %>% rowwise %>% mutate(step10=if_else(
      #   a==inputs[j-1] & b==inputs[j],step10+cc,step10)
      #   )->>pairs
      pairs$step10[pairs$a==inputs[j-1] & pairs$b==inputs[j]]<<-pairs$step10[pairs$a==inputs[j-1] & pairs$b==inputs[j]] + c
    }
  }
}

pmap(pairs %>% select(a,c,b),fill10)



# How many appearances of pair(a,b) after 20 steps
fill20<-function(a,step10,b){
  if(step10>0){
    s<-pairTable %>% filter(x1==a,x2==b,n==10) %>% select(res) %>% 
      unlist %>% unname
    inputs<-str_split(s,'') %>% unlist
    #print(inputs)
    for(j in 2:length(inputs)){
      pairs$step20[pairs$a==inputs[j-1] & pairs$b==inputs[j]]<<-pairs$step20[pairs$a==inputs[j-1] & pairs$b==inputs[j]] + step10
    }
  }
}

pmap(pairs %>% select(a,step10,b),fill20)

# How many appearances of pair(a,b) after 30 steps
fill30<-function(a,step20,b){
  if(step20>0){
    s<-pairTable %>% filter(x1==a,x2==b,n==10) %>% select(res) %>% 
      unlist %>% unname
    inputs<-str_split(s,'') %>% unlist
    #print(inputs)
    for(j in 2:length(inputs)){
      pairs$step30[pairs$a==inputs[j-1] & pairs$b==inputs[j]]<<-pairs$step30[pairs$a==inputs[j-1] & pairs$b==inputs[j]] + step20
    }
  }
}

pmap(pairs %>% select(a,step20,b),fill30)

# How many appearances of pair(a,b) after 40 steps
fill40<-function(a,step30,b){
  if(step30>0){
    s<-pairTable %>% filter(x1==a,x2==b,n==10) %>% select(res) %>% 
      unlist %>% unname
    inputs<-str_split(s,'') %>% unlist
    #print(inputs)
    for(j in 2:length(inputs)){
      pairs$step40[pairs$a==inputs[j-1] & pairs$b==inputs[j]]<<-pairs$step40[pairs$a==inputs[j-1] & pairs$b==inputs[j]] + step30
    }
  }
}

pmap(pairs %>% select(a,step30,b),fill40)

# Counting each letter appearance
sumsB<-rep(0,10)
names(sumsB)<-names(sums)
j<-1
for(j in 1:10){
  car<-names(sumsB)[j]
  sumsB[j]<-sumsB[j] + (pairs %>% filter(a==car) %>% summarise(sum(step40)) %>% unlist %>% unname)
  sumsB[j]<-sumsB[j] + (pairs %>% filter(b==car) %>% summarise(sum(step40)) %>% unlist %>% unname)
}

# first and last letter are not counted twice yet
sumsB<-sumsB+as.integer(names(sumsB) %in% c("C","F"))
# each is counted twice
sumsB<-sumsB/2

max(sumsB)-min(sumsB)

# 3015383850689
